from __future__ import annotations

from io import BytesIO
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw, ImageFont


PAGE_SIZE = (1240, 1754)
BG = "#F4F7FB"
INK = "#123047"
MUTED = "#5A7184"
CARD = "#FFFFFF"
NAVY = "#0F2742"
TEAL = "#18B7A8"
GOLD = "#E8B14A"
LIGHT = "#DDE8F2"


def _font(size: int, bold: bool = False):
    candidates = ["DejaVuSans-Bold.ttf", "arialbd.ttf"] if bold else ["DejaVuSans.ttf", "arial.ttf"]
    for candidate in candidates:
        try:
            return ImageFont.truetype(candidate, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


def _draw_rounded_card(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], fill: str) -> None:
    draw.rounded_rectangle(box, radius=30, fill=fill)


def _money(value: Any) -> str:
    try:
        return f"Rs {float(value):,.2f}"
    except (TypeError, ValueError):
        return f"Rs {value}"


def _bullet_lines(title: str, payload: dict[str, Any]) -> list[str]:
    lines = [title]
    for key, value in payload.items():
        label = str(key).replace("_", " ").title()
        lines.append(f"{label}: {_money(value) if isinstance(value, (int, float)) else value}")
    return lines


def _build_cover_page(draft_packet: dict[str, Any], review_payload: dict[str, Any]) -> Image.Image:
    image = Image.new("RGB", PAGE_SIZE, BG)
    draw = ImageDraw.Draw(image)

    title_font = _font(56, bold=True)
    h1_font = _font(28, bold=True)
    body_font = _font(22)
    small_font = _font(18)

    draw.rectangle((0, 0, PAGE_SIZE[0], 260), fill=NAVY)
    draw.ellipse((920, -120, 1280, 220), fill=TEAL)
    draw.ellipse((840, 60, 1100, 320), fill=GOLD)

    draw.text((80, 72), "TaxAI Filing Pack", font=title_font, fill="white")
    draw.text((82, 150), "AI-prepared draft return for user review", font=body_font, fill="#D7E8F6")

    _draw_rounded_card(draw, (70, 320, 1170, 720), CARD)
    draw.text((110, 370), "Return Overview", font=h1_font, fill=INK)

    overview_lines = [
        f"Job ID: {draft_packet.get('job_id', '-')}",
        f"Suggested ITR Form: {draft_packet.get('suggested_itr_form', '-')}",
        f"Profile Type: {str(draft_packet.get('profile_type', '-')).replace('_', ' ').title()}",
        f"Financial Year: {draft_packet.get('financial_year', '-')}",
        f"Regime: {str(draft_packet.get('regime', '-')).title()}",
        f"Ready For Approval: {'Yes' if review_payload.get('ready_for_approval') else 'No'}",
    ]
    y = 435
    for line in overview_lines:
        draw.text((110, y), line, font=body_font, fill=MUTED)
        y += 42

    summary = draft_packet.get("itr_fields", {})
    metric_boxes = [
        ("Gross Income", _money(summary.get("gross_total_income", 0))),
        ("Taxable Income", _money(summary.get("taxable_income", 0))),
        ("Liability", _money(summary.get("total_tax_liability", 0))),
        ("Refund / Payable", _money(summary.get("refund_due", 0) or summary.get("balance_tax_payable", 0))),
    ]
    start_x = 70
    for index, (label, value) in enumerate(metric_boxes):
        left = start_x + index * 275
        _draw_rounded_card(draw, (left, 770, left + 245, 960), CARD)
        draw.rectangle((left, 770, left + 245, 790), fill=TEAL if index % 2 == 0 else GOLD)
        draw.text((left + 24, 825), label, font=small_font, fill=MUTED)
        draw.text((left + 24, 875), value, font=h1_font, fill=INK)

    _draw_rounded_card(draw, (70, 1020, 1170, 1600), CARD)
    draw.text((110, 1070), "Review Notes", font=h1_font, fill=INK)

    blockers = review_payload.get("review_blockers", [])
    tasks = review_payload.get("review_tasks", [])
    note_lines = [
        f"Blockers detected: {len(blockers)}",
        f"Review tasks detected: {len(tasks)}",
    ]
    for blocker in blockers[:6]:
        note_lines.append(f"- {blocker.get('field', 'item')}: {blocker.get('message', '')}")

    y = 1135
    for line in note_lines:
        draw.text((110, y), line, font=body_font, fill=MUTED)
        y += 40

    draw.text((80, 1660), "Generated by TaxAI", font=small_font, fill="#7B90A3")
    return image


def _build_detail_page(draft_packet: dict[str, Any]) -> Image.Image:
    image = Image.new("RGB", PAGE_SIZE, BG)
    draw = ImageDraw.Draw(image)

    h1_font = _font(38, bold=True)
    h2_font = _font(26, bold=True)
    body_font = _font(22)
    small_font = _font(18)

    draw.rectangle((0, 0, PAGE_SIZE[0], 180), fill=NAVY)
    draw.text((80, 60), "Income, Deductions and Credits", font=h1_font, fill="white")

    sections = [
        ("Income Schedule", draft_packet.get("income_schedule", {}), (70, 240, 590, 1460)),
        ("Deduction Schedule", draft_packet.get("deduction_schedule", {}), (650, 240, 1170, 980)),
        ("Credit Schedule", draft_packet.get("credit_schedule", {}), (650, 1030, 1170, 1460)),
    ]

    for title, payload, box in sections:
        _draw_rounded_card(draw, box, CARD)
        draw.text((box[0] + 34, box[1] + 28), title, font=h2_font, fill=INK)
        y = box[1] + 92
        for line in _bullet_lines(title, payload)[1:]:
            draw.text((box[0] + 34, y), line, font=body_font, fill=MUTED)
            y += 38

    _draw_rounded_card(draw, (70, 1510, 1170, 1660), CARD)
    draw.text((104, 1555), "Draft return only. User review required before any future e-filing.", font=small_font, fill=MUTED)
    return image


def render_itr_pdf(draft_packet: dict[str, Any], review_payload: dict[str, Any]) -> bytes:
    pages = [
        _build_cover_page(draft_packet, review_payload).convert("RGB"),
        _build_detail_page(draft_packet).convert("RGB"),
    ]
    buffer = BytesIO()
    pages[0].save(buffer, format="PDF", resolution=150.0, save_all=True, append_images=pages[1:])
    return buffer.getvalue()


def save_itr_pdf(output_dir: str, filename: str, draft_packet: dict[str, Any], review_payload: dict[str, Any]) -> str:
    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)
    file_path = path / filename
    file_path.write_bytes(render_itr_pdf(draft_packet, review_payload))
    return str(file_path)
